USE [master]
GO

/****** Object:  Database [BiciCoruña]    Script Date: 19/05/2023 10:38:04 ******/
CREATE DATABASE [BiciCoruña]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BiciCoruña', FILENAME = N'C:\Proyecto\BiciCoruña.mdf' , SIZE = 10240KB , MAXSIZE = 51200KB , FILEGROWTH = 5120KB ), 
 FILEGROUP [BiciCoruña_mod] CONTAINS MEMORY_OPTIMIZED_DATA  DEFAULT
( NAME = N'BiciCoruña_mod1', FILENAME = N'c:\Proyecto\BiciCoruña' , MAXSIZE = UNLIMITED)
 LOG ON 
( NAME = N'BiciCoruña_log', FILENAME = N'C:\Proyecto\BiciCoruña_log.ldf' , SIZE = 5120KB , MAXSIZE = 25600KB , FILEGROWTH = 5120KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BiciCoruña].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BiciCoruña] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BiciCoruña] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BiciCoruña] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BiciCoruña] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BiciCoruña] SET ARITHABORT OFF 
GO

ALTER DATABASE [BiciCoruña] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BiciCoruña] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BiciCoruña] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BiciCoruña] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BiciCoruña] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BiciCoruña] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BiciCoruña] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BiciCoruña] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BiciCoruña] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BiciCoruña] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BiciCoruña] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BiciCoruña] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BiciCoruña] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BiciCoruña] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BiciCoruña] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BiciCoruña] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BiciCoruña] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BiciCoruña] SET RECOVERY FULL 
GO

ALTER DATABASE [BiciCoruña] SET  MULTI_USER 
GO

ALTER DATABASE [BiciCoruña] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BiciCoruña] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BiciCoruña] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BiciCoruña] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BiciCoruña] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BiciCoruña] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BiciCoruña] SET ENCRYPTION ON
GO

ALTER DATABASE [BiciCoruña] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BiciCoruña] SET  READ_WRITE 
GO

